name: Agroproject
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: install dependancies
        run: |
          cd Flask_project
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
       
    
      
